/**
 * PDF export regressions (lib/testing/pdf.ts + the export control).
 *
 * The failure these guard against was real and mobile-specific: the export
 * promised a PDF, but every print-based delivery path was unreliable on
 * iPhone, the microphone test fell back to a TXT, and the CPS flow navigated
 * the tab away (losing the result the user came to export).
 *
 * These tests check the PDF is STRUCTURALLY VALID, not merely generated: a
 * file with a bad cross-reference table or a malformed object table is
 * rejected by real PDF readers, so the assertions below parse the bytes the
 * way a reader would.
 */
import test from 'node:test';
import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';

import { buildPdf, toPdfText, wrapLine, pdfFilename, reportLinesFromText } from '../lib/testing/pdf';
import { buildExportReport, buildPrintReport } from '../lib/testing/exportReport';

const repoRoot = join(dirname(fileURLToPath(import.meta.url)), '..');
const controlSource = readFileSync(join(repoRoot, 'components/ui/ExportReportControl.tsx'), 'utf8');

/** Decode the generated bytes back to a latin-1 string for structural checks. */
function decode(bytes: Uint8Array): string {
  let out = '';
  for (const b of bytes) out += String.fromCharCode(b);
  return out;
}

const SIMPLE = {
  title: 'DeviceTry - Local Test Report',
  lines: [
    { text: 'DeviceTry - Local Test Report', style: 'bold' as const },
    { text: 'Test: CPS & Spacebar Test' },
    { text: 'Completion status: Measured (completed, neutral)' },
  ],
};

test('pdf - produces a structurally valid PDF 1.4 file', () => {
  const text = decode(buildPdf(SIMPLE));
  assert.ok(text.startsWith('%PDF-1.4'), 'starts with the PDF 1.4 header');
  assert.ok(text.trimEnd().endsWith('%%EOF'), 'ends with the EOF marker');
  assert.match(text, /\/Type\s*\/Catalog/, 'has a document catalog');
  assert.match(text, /\/Type\s*\/Pages/, 'has a page tree');
  assert.match(text, /\/Type\s*\/Page\b/, 'has at least one page');
  assert.match(text, /\/Type\s*\/Font/, 'declares a font resource');
});

test('pdf - the cross-reference table points at the real byte offsets', () => {
  const bytes = buildPdf(SIMPLE);
  const text = decode(bytes);
  const startxrefMatch = text.match(/startxref\s+(\d+)/);
  assert.ok(startxrefMatch, 'startxref is present');

  const xrefStart = Number(startxrefMatch![1]);
  assert.ok(text.startsWith('xref', xrefStart), `xref table begins at ${xrefStart}`);

  // Parse the xref entries and verify each offset lands exactly on "N 0 obj".
  const xrefBody = text.slice(xrefStart);
  const entries = [...xrefBody.matchAll(/^(\d{10}) 00000 n\s*$/gm)].map((m) => Number(m[1]));
  assert.ok(entries.length >= 5, `at least five in-use objects (got ${entries.length})`);

  entries.forEach((offset, index) => {
    const objectNumber = index + 1; // entry 0 is the free head, then 1..n
    assert.ok(
      text.startsWith(`${objectNumber} 0 obj`, offset),
      `xref entry for object ${objectNumber} points at its real offset ${offset}`
    );
  });
});

test('pdf - reports more than one page when the content overflows', () => {
  const many = {
    title: 'Long report',
    lines: Array.from({ length: 220 }, (_, i) => ({ text: `Line ${i + 1}: measurement output` })),
  };
  const text = decode(buildPdf(many));
  const countMatch = text.match(/\/Count (\d+)/);
  assert.ok(countMatch, 'page tree declares a count');
  assert.ok(Number(countMatch![1]) > 1, 'long content paginates');
});

test('pdf - escapes PDF-structural characters so the file cannot break', () => {
  assert.equal(toPdfText('a(b)c\\d'), 'a\\(b\\)c\\\\d');
  const text = decode(buildPdf({ title: 'x', lines: [{ text: 'weird (parens) and \\ backslash' }] }));
  assert.ok(
    text.includes('(weird \\(parens\\) and \\\\ backslash) Tj'),
    'parens and backslashes are escaped inside the text operator'
  );
});

test('pdf - transliterates non-Latin-1 characters instead of emitting raw bytes', () => {
  // Smart quotes, em dash, ellipsis and a non-Latin glyph must all become
  // representable characters, never malformed bytes.
  const converted = toPdfText('\u201cquoted\u201d \u2014 dash \u2026 \u00b7 \u4e2d');
  for (const ch of converted) {
    const code = ch.charCodeAt(0);
    assert.ok(code >= 0x20 && code <= 0x7e, `character ${JSON.stringify(ch)} is plain printable ASCII`);
  }
  assert.match(converted, /"quoted"/);
  assert.match(converted, /- dash/);
  assert.match(converted, /\.\.\./);
});

test('pdf - wraps long lines and never emits an overlong line', () => {
  assert.deepEqual(wrapLine('short', 20), ['short']);
  const wrapped = wrapLine('alpha beta gamma delta epsilon zeta', 12);
  assert.ok(wrapped.length > 1, 'long text is split');
  for (const line of wrapped) assert.ok(line.length <= 12, `"${line}" fits the budget`);

  // An unbreakable token is split rather than overflowing the page.
  const hard = wrapLine('x'.repeat(45), 20);
  assert.equal(hard.length, 3);
  for (const line of hard) assert.ok(line.length <= 20);
});

test('pdf - an empty document is still a valid file', () => {
  const text = decode(buildPdf({ title: 'Empty', lines: [] }));
  assert.ok(text.startsWith('%PDF-1.4'));
  assert.ok(text.trimEnd().endsWith('%%EOF'));
  assert.match(text, /\/Count 1/, 'still has one page');
});

test('pdf - filenames are filesystem safe and timestamped', () => {
  const name = pdfFilename('microphone-test', Date.UTC(2026, 8, 24, 12, 30, 15));
  assert.equal(name, 'devicetry-microphone-test-2026-09-24T12-30-15-000Z.pdf');
  assert.ok(name.endsWith('.pdf'));
  assert.ok(!/[:*?"<>|]/.test(name), 'no characters that are illegal in filenames');
});

/* ------------------------------------------------------------------ */
/* The PDF is built from the same previewed, privacy-checked data        */
/* ------------------------------------------------------------------ */

const TOOL = {
  id: 'microphone-test',
  title: 'Microphone Test',
  slug: 'microphone-test',
  instructions: ['Click Start Test to grant microphone permission.'],
  limitations: ['Digital meter readings reflect browser input gain, not calibrated SPL.'],
};

test('pdf - excludes the device label by default and includes it only on opt-in', () => {
  const result = {
    status: 'measured' as const,
    details: 'Usable input signal observed.',
    metrics: { peakLevelPercent: 41, deviceLabel: 'Blue Snowball Microphone' },
  };
  const now = Date.UTC(2026, 8, 24);

  const withoutLabel = buildExportReport(TOOL, result, now, { includeSensitive: false });
  const textDefault = buildPrintReport(withoutLabel, 'https://devicetry.mcfoxfasty.workers.dev');
  assert.ok(!textDefault.includes('Blue Snowball'), 'device label is absent unless opted in');
  assert.match(textDefault, /Excluded by your export choice/, 'the exclusion is stated, not hidden');

  const withLabel = buildExportReport(TOOL, result, now, { includeSensitive: true });
  const textOptIn = buildPrintReport(withLabel, 'https://devicetry.mcfoxfasty.workers.dev');
  assert.match(textOptIn, /Blue Snowball/, 'an explicit opt-in includes the label');
});

test('pdf - the generated PDF carries the opted-in report text, nothing more', () => {
  const data = buildExportReport(
    TOOL,
    {
      status: 'measured' as const,
      details: 'Usable input signal observed.',
      metrics: { peakLevelPercent: 41, deviceLabel: 'Studio Mic' },
    },
    Date.UTC(2026, 8, 24),
    { includeSensitive: true }
  );
  const model = reportLinesFromText(buildPrintReport(data, 'https://devicetry.mcfoxfasty.workers.dev'));
  const text = decode(buildPdf({ title: model.title, lines: model.lines }));

  assert.match(text, /Microphone Test/, 'the test name is present');
  assert.match(text, /peakLevelPercent/, 'measurements are present');
  assert.match(text, /Studio Mic/, 'opted-in device label is present');
  // The PDF carries the report text only. The word "recording" appears in
  // the privacy notice itself; what must never appear is an actual address.
  assert.ok(
    !/\b\d{1,3}\.\d{1,3}\.\d{1,3}\.\d{1,3}\b/.test(text),
    'no IP addresses are present in the PDF'
  );
});

test('pdf - the report text model marks section headings as bold', () => {
  const model = reportLinesFromText(
    [
      'DeviceTry - Local Test Report',
      'Test: CPS & Spacebar Test',
      'Limitations',
      '  - A limitation.',
    ].join('\n')
  );
  assert.equal(model.lines[0].style, 'bold', 'title is bold');
  assert.equal(model.lines[1].style, 'bold', 'a "Test:" line is a heading');
  assert.equal(model.lines[3].text, 'A limitation.', 'list indentation is stripped for layout');
  assert.equal(model.lines[3].style, 'normal', 'list items are body text');
});

/* ------------------------------------------------------------------ */
/* Delivery never navigates away and never mislabels a text file        */
/* ------------------------------------------------------------------ */

test('export flow - no pop-up, no tab navigation, no print() call', () => {
  // These are the three mechanisms that failed on iPhone: the pop-up was
  // blocked, the navigation discarded the test result, and print() did
  // nothing useful on a blob document.
  assert.ok(!/window\.open\(/.test(controlSource), 'no pop-up window is opened');
  assert.ok(!/window\.location\.assign/.test(controlSource), 'the tab is never navigated');
  assert.ok(!/location\.href\s*=/.test(controlSource), 'no location assignment');
  assert.ok(!/\.print\(\)/.test(controlSource), 'no reliance on window.print()');
});

test('export flow - the PDF is generated locally from the previewed data', () => {
  assert.match(controlSource, /buildPdf\(/, 'the PDF writer is used');
  assert.match(controlSource, /buildPrintReport\(data, origin \|\| undefined\)/, 'built from the previewed data model');
  assert.match(controlSource, /buildPdf\(\{ title: model\.title, lines: model\.lines \}\)/);
});

test('export flow - delivery prefers the share sheet and falls back to a download', () => {
  assert.match(controlSource, /nav\.canShare\(\{ files: \[file\] \}\)/, 'file sharing is attempted when supported');
  assert.match(controlSource, /a\.download = filename/, 'a real download anchor is the fallback');
  assert.match(controlSource, /pdfBlob\(bytes, model\.title\)/, 'a real PDF blob is produced');
});

test('export flow - the text fallback is offered only after a failure and is never called a PDF', () => {
  assert.match(controlSource, /The PDF could not be created on this device/, 'failure is stated plainly');
  assert.match(controlSource, /Download a plain-text \(\.txt\) report instead/);
  assert.match(controlSource, /The \.txt file is not a PDF/);
  // No button may promise a PDF while delivering text.
  assert.ok(
    !/>Download PDF report<\/[\s\S]{0,400}downloadTextReport\(\)/.test(controlSource),
    'the PDF button never triggers the text download'
  );
});

test('export flow - CSV stays a separate, independent download', () => {
  assert.match(controlSource, /Download CSV \(measurements\)/, 'CSV is its own action');
  assert.match(controlSource, /const downloadCsv = useCallback/, 'CSV generation is separate from the PDF path');
  assert.match(controlSource, /text\/csv/, 'CSV keeps its own MIME type');
});
