import { ToolDefinition, ToolCategory } from './types';

export type { ToolDefinition, ToolCategory } from './types';

/**
 * Phase 9 final primary catalog — exactly 15 tools.
 * Supporting diagnostics (permission-diagnostics, browser-compatibility,
 * codec-support, webrtc-test, browser-system-info,
 * devicetry-storage-inspector) live in SUPPORTING_REGISTRY below: they get
 * pages under /test/ but are not primary catalog cards.
 */
export const TOOLS_REGISTRY: ToolDefinition[] = [
  {
    id: 'microphone-test',
    slug: 'microphone-test',
    category: 'audio-video' as ToolCategory,
    categoryLabel: 'Audio & Video',
    title: 'Microphone Test',
    shortDesc: 'Live input level meter with pitch detection and voice recorder tabs.',
    supportHint: 'Requires microphone permission',
    keywords: ['mic test', 'microphone test', 'audio input', 'test mic online', 'pitch detector', 'voice recorder'],
    iconType: 'microphone',
    requiredApis: ['navigator.mediaDevices.getUserMedia', 'AudioContext'],
    componentName: 'MicrophoneTester',
    tabId: 'level',
    relatedToolIds: ['voice-recorder', 'speakers-test', 'webcam-test'],
    supportLinks: [
      { label: 'Microphone permission help', href: '/test/permission-diagnostics' },
      { label: 'Microphone not working — troubleshooting guide', href: '/guides/microphone-not-working' },
    ],
    instructions: [
      'Click Start Test to grant microphone permission.',
      'Speak into your microphone and observe the live relative input level and waveform.',
      'Open the Pitch tab to detect musical pitch, or the Recorder tab to record and replay a 5-second sample.',
    ],
    limitations: [
      'Digital meter readings reflect browser input gain, not calibrated acoustic sound pressure (SPL).',
      'Noise suppression applied by your operating system or browser may alter waveforms.',
    ],
    troubleshooting: [
      'If permission is blocked, click the lock icon in your browser address bar and allow microphone access.',
      'Check that your headset or external mic is selected in the device dropdown.',
    ],
  },
  {
    id: 'webcam-test',
    slug: 'webcam-test',
    category: 'audio-video' as ToolCategory,
    categoryLabel: 'Audio & Video',
    title: 'Webcam Test',
    shortDesc: 'Inspect live camera stream, delivered resolution and frame rate — with a mirror mode.',
    supportHint: 'Requires camera permission',
    keywords: ['webcam test', 'camera test', 'test camera online', 'online mirror', 'webcam mirror'],
    iconType: 'webcam',
    requiredApis: ['navigator.mediaDevices.getUserMedia'],
    componentName: 'WebcamTester',
    tabId: 'test',
    relatedToolIds: ['microphone-test', 'speakers-test', 'screen-test'],
    supportLinks: [
      { label: 'Camera permission help', href: '/test/permission-diagnostics' },
      { label: 'Webcam not working — troubleshooting guide', href: '/guides/webcam-not-working' },
    ],
    instructions: [
      'Click Start Test to request camera access.',
      'View the stream properties, delivered resolution, and observed frame cadence.',
      'Switch to the Mirror tab for a full-screen, flipped preview you can use while grooming or framing a shot.',
    ],
    limitations: [
      'Delivered resolution depends on browser WebRTC constraints and hardware driver limits.',
      'Observed FPS measures video frame delivery rate, not display refresh rate.',
    ],
    troubleshooting: [
      'Ensure no other application (Zoom, Teams, OBS) is exclusively holding the camera lock.',
      'Unplug and reconnect external USB webcams if no stream appears.',
    ],
  },
  {
    id: 'speakers-test',
    slug: 'speakers-test',
    category: 'audio-video' as ToolCategory,
    categoryLabel: 'Audio & Video',
    title: 'Speaker & Headphone Test',
    shortDesc: 'Verify stereo separation with independent left, right, both, and bass tone checks.',
    supportHint: 'Requires Web Audio API',
    keywords: ['speaker test', 'sound test', 'audio test', 'left right audio test', 'stereo test', 'bass test'],
    iconType: 'headphones',
    requiredApis: ['AudioContext'],
    componentName: 'SpeakersTester',
    relatedToolIds: ['tone-generator', 'microphone-test', 'voice-recorder'],
    supportLinks: [
      { label: 'One side silent? Read the guide', href: '/guides/one-headphone-side-not-working' },
    ],
    instructions: [
      'Set your system volume to a moderate level.',
      'Play the left, right, and combined-channel tones in turn and confirm what you actually hear.',
      'Use the bass check for a low-frequency tone; confirm audibility, it does not rate headphone quality.',
    ],
    limitations: [
      'Audible output verification relies on human listening confirmation — playing a tone alone proves nothing.',
      'Bluetooth headphones with mono hands-free profiles may mix both channels together.',
      'A bass playback check confirms low-frequency output only; it does not measure hearing or audio hardware quality.',
    ],
    troubleshooting: [
      'Make sure your physical mute switch or volume knob is not turned down.',
      'Check your operating system sound output device.',
    ],
  },
  {
    id: 'voice-recorder',
    slug: 'voice-recorder',
    category: 'audio-video' as ToolCategory,
    categoryLabel: 'Audio & Video',
    title: 'Online Voice Recorder',
    shortDesc: 'Record audio locally with pause/resume, playback, and download — nothing uploaded.',
    supportHint: 'Requires MediaRecorder API',
    keywords: ['voice recorder', 'audio recorder', 'record mic online', 'voice memo'],
    iconType: 'microphone',
    requiredApis: ['navigator.mediaDevices.getUserMedia', 'MediaRecorder'],
    componentName: 'VoiceRecorderTester',
    relatedToolIds: ['microphone-test', 'speakers-test', 'tone-generator'],
    supportLinks: [
      { label: 'Recording sounds too quiet?', href: '/guides/microphone-too-quiet' },
    ],
    instructions: [
      'Click Start Recording to begin capturing audio.',
      'Use Pause/Resume as needed, then click Stop when finished.',
      'Play back your recording and click Download to save the file locally.',
    ],
    limitations: [
      'Recordings are stored purely in browser memory and capped at 5 minutes.',
      "The download container depends on your browser's supported codecs (typically WebM, or Ogg in Firefox); the file extension always matches the actual recording.",
    ],
    troubleshooting: [
      'If the audio is silent, verify the correct microphone is selected.',
      'Check that microphone permissions are allowed in the browser.',
    ],
  },
  {
    id: 'tone-generator',
    slug: 'tone-generator',
    category: 'audio-video' as ToolCategory,
    categoryLabel: 'Audio & Video',
    title: 'Tone Generator',
    shortDesc: 'Play reference tones at any frequency with sine, square, sawtooth, and triangle waves.',
    supportHint: 'Requires Web Audio API',
    keywords: ['tone generator', 'frequency generator', 'sine wave', 'test tone', 'bass tone'],
    iconType: 'headphones',
    requiredApis: ['AudioContext'],
    componentName: 'ToneGeneratorTester',
    relatedToolIds: ['speakers-test', 'voice-recorder', 'microphone-test'],
    instructions: [
      'Choose a frequency and waveform, then press Play.',
      'Adjust volume gradually — start low to protect your ears and speakers.',
      'Use the preset frequencies to check channel response across the audible range.',
    ],
    limitations: [
      'Sustained high volumes can damage hearing and speakers; keep levels moderate.',
      'Output frequency response depends on your playback hardware, not the generator.',
    ],
    troubleshooting: [
      'No sound? Check that the correct output device is selected and volume is up.',
      'Bluetooth devices may filter very low or very high frequencies.',
    ],
  },
  {
    id: 'keyboard-test',
    slug: 'keyboard-test',
    category: 'input-devices' as ToolCategory,
    categoryLabel: 'Input & Gaming',
    title: 'Keyboard Test',
    shortDesc: 'Press every key to verify registration, key rollover, and ghosting visually.',
    supportHint: 'Works with any keyboard layout',
    keywords: ['keyboard test', 'key test', 'keyboard tester', 'rollover test', 'ghosting test'],
    iconType: 'keyboard',
    requiredApis: ['Keyboard Events'],
    componentName: 'KeyboardTester',
    relatedToolIds: ['mouse-test', 'gamepad-test', 'click-speed-test'],
    supportLinks: [
      { label: 'Keys not registering? Read the guide', href: '/guides/keyboard-keys-not-registering' },
    ],
    instructions: [
      'Click the test area and press each physical key on your keyboard.',
      'Highlighted keys have registered; keys that stay dark are not being received.',
      'Hold multiple keys together to check rollover behavior.',
    ],
    limitations: [
      'Multimedia and Fn-only keys may be captured by the operating system before the browser.',
      'On some laptops the embedded controller filters certain key combinations.',
    ],
    troubleshooting: [
      'Test in another browser to rule out extension interference.',
      'Wireless keyboards: replace the battery and re-pair the dongle.',
    ],
  },
  {
    id: 'mouse-test',
    slug: 'mouse-test',
    category: 'input-devices' as ToolCategory,
    categoryLabel: 'Input & Gaming',
    title: 'Mouse Test',
    shortDesc: 'Verify left, right, and middle buttons, scroll wheel, and tracking accuracy.',
    supportHint: 'Works with touchpads and mice',
    keywords: ['mouse test', 'mouse tester', 'button test', 'scroll test', 'double click test'],
    iconType: 'mouse',
    requiredApis: ['Pointer Events'],
    componentName: 'MouseTester',
    relatedToolIds: ['keyboard-test', 'click-speed-test', 'gamepad-test'],
    supportLinks: [
      { label: 'Unwanted double-clicking? Read the guide', href: '/guides/mouse-double-clicking' },
    ],
    instructions: [
      'Click inside the test area with each mouse button and watch each one register.',
      'Scroll to verify the wheel direction and detents.',
      'Move the cursor around to confirm smooth tracking without jumps.',
    ],
    limitations: [
      'Browsers suppress the context menu inside the test area; this is expected.',
      'DPI and pointer acceleration are OS-level settings and are not measured here.',
    ],
    troubleshooting: [
      'A chattering button registering double clicks points to switch wear — see the guide.',
      'Try a different USB port or replace wireless batteries first.',
    ],
  },
  {
    id: 'gamepad-test',
    slug: 'gamepad-test',
    category: 'input-devices' as ToolCategory,
    categoryLabel: 'Input & Gaming',
    title: 'Gamepad Test',
    shortDesc: 'Press every controller button, move both sticks, and run a neutral drift check.',
    supportHint: 'Press any button to connect',
    keywords: ['gamepad test', 'controller test', 'gamepad tester', 'stick drift test', 'joystick test'],
    iconType: 'gamepad',
    requiredApis: ['Gamepad API'],
    componentName: 'GamepadTester',
    relatedToolIds: ['keyboard-test', 'mouse-test', 'touchscreen-test'],
    supportLinks: [
      { label: 'Stick drift? Read the guide', href: '/guides/controller-stick-drift' },
    ],
    instructions: [
      'Connect your controller by USB or Bluetooth and press any button.',
      'Watch each button and stick axis register in real time.',
      'Run the Neutral Drift Check with the sticks untouched for 2.5 seconds.',
    ],
    limitations: [
      'Connection alone does not verify every button — press each control to observe it.',
      'The drift threshold is this tool\u2019s approximate heuristic, not a manufacturer certification.',
    ],
    troubleshooting: [
      'Controller not detected? Press a button while the page is focused to wake the browser API.',
      'Some controllers need xpad/xone drivers on Linux or Steam Input to appear.',
    ],
  },
  {
    id: 'touchscreen-test',
    slug: 'touchscreen-test',
    category: 'input-devices' as ToolCategory,
    categoryLabel: 'Input & Gaming',
    title: 'Touchscreen Test',
    shortDesc: 'Touch each coverage tile and test multi-touch — mouse input never counts.',
    supportHint: 'Requires a touch-capable display',
    keywords: ['touchscreen test', 'touch test', 'multi touch test', 'touch screen checker'],
    iconType: 'touch',
    requiredApis: ['Pointer Events'],
    componentName: 'TouchscreenTester',
    tabId: 'touch',
    relatedToolIds: ['gamepad-test', 'mouse-test', 'screen-test'],
    instructions: [
      'Drag your finger across every tile until the full grid registers coverage.',
      'Open the Multi-Touch tab and place as many fingers as possible to observe simultaneous touches.',
      'Mouse clicks are tracked separately and never count as touch verification.',
    ],
    limitations: [
      'A single covered tile does not prove the whole screen works — cover every tile.',
      'Pen input is reported separately from finger touches.',
    ],
    troubleshooting: [
      'Clean the screen; some protectors reduce sensitivity at edges.',
      'If no touches register, verify the touch driver in Device Manager or System Settings.',
    ],
  },
  {
    id: 'click-speed-test',
    slug: 'click-speed-test',
    category: 'input-devices' as ToolCategory,
    categoryLabel: 'Input & Gaming',
    title: 'CPS & Spacebar Test',
    shortDesc: 'Measure clicks or spacebar presses per second over a bounded 5/10/30-second run.',
    supportHint: 'Bounded timed runs',
    keywords: ['cps test', 'click speed test', 'clicks per second', 'spacebar test', 'click counter'],
    iconType: 'mouse',
    requiredApis: ['Pointer Events', 'Keyboard Events'],
    componentName: 'ClickSpeedTester',
    relatedToolIds: ['reaction-time-test', 'mouse-test', 'keyboard-test'],
    instructions: [
      'Choose 5, 10, or 30 seconds, then start clicking (or pressing spacebar) when the timer begins.',
      'Your first click starts the run; the counter stops automatically at the end.',
      'Use Restart to run again — results are honest counts, no rankings or percentiles.',
    ],
    limitations: [
      'Results depend on your input device and browser timing; they are not universal skill ratings.',
      'Freeform (unbounded) counting is intentionally not offered — runs are bounded.',
    ],
    troubleshooting: [
      'Inconsistent counts? Disable browser features that throttle background timers.',
      'A mouse registering double inputs per click has a worn switch — see the mouse guide.',
    ],
  },
  {
    id: 'reaction-time-test',
    slug: 'reaction-time-test',
    category: 'input-devices' as ToolCategory,
    categoryLabel: 'Input & Gaming',
    title: 'Reaction Time Test',
    shortDesc: 'Measure visual response time over five attempts with a randomized wait.',
    supportHint: 'Five attempts per session',
    keywords: ['reaction time test', 'reaction tester', 'reflex test', 'response time'],
    iconType: 'gauge',
    requiredApis: ['performance.now()', 'Pointer Events'],
    componentName: 'ReactionTimeTester',
    relatedToolIds: ['click-speed-test', 'mouse-test', 'gamepad-test'],
    instructions: [
      'Press Start, wait for the panel to turn green, then click, tap, or press any key immediately.',
      'Clicking too early invalidates that attempt — wait for the green signal.',
      'Complete five valid attempts; the tool shows each time, your best, and the median.',
    ],
    limitations: [
      'Screen refresh latency, input-device latency, and browser scheduling all affect results.',
      'This is a browser-timing measurement — not a medical or cognitive assessment.',
    ],
    troubleshooting: [
      'Extremely inconsistent values usually mean background throttling or a busy CPU.',
      'Use a wired mouse and a fullscreen window for the most repeatable conditions.',
    ],
  },
  {
    id: 'screen-test',
    slug: 'screen-test',
    category: 'display' as ToolCategory,
    categoryLabel: 'Display & Screen',
    title: 'Screen Test',
    shortDesc: 'Dead-pixel, solid-pattern, and display-information checks in one tool.',
    supportHint: 'Fullscreen recommended',
    keywords: ['screen test', 'dead pixel test', 'display test', 'pixel checker', 'screen info'],
    iconType: 'monitor',
    requiredApis: ['Fullscreen API'],
    componentName: 'ScreenTestHub',
    tabId: 'dead-pixel',
    relatedToolIds: ['refresh-rate-test', 'webcam-test', 'touchscreen-test'],
    supportLinks: [
      { label: 'How to check for dead pixels', href: '/guides/checking-screen-dead-pixels' },
    ],
    instructions: [
      'Open the Dead Pixel tab and step through each solid color at fullscreen, looking for dots.',
      'Use the Patterns tab for gradients and grids that expose uniformity and banding.',
      'The Screen Info tab reports your display\u2019s browser-visible resolution and orientation.',
    ],
    limitations: [
      'A browser cannot read the physical panel; manufacturer specs may differ from what is reported.',
      'One clean pass over one color does not guarantee a flawless panel — check every color.',
    ],
    troubleshooting: [
      'Mark persistent bright/dark dots across colors as genuine pixel defects.',
      'Images that disappear on the next frame are likely software, not hardware.',
    ],
  },
  {
    id: 'refresh-rate-test',
    slug: 'refresh-rate-test',
    category: 'display' as ToolCategory,
    categoryLabel: 'Display & Screen',
    title: 'Refresh Rate Test',
    shortDesc: 'Measure browser frame timing to estimate your display\u2019s rendering cadence.',
    supportHint: 'Browser rendering timing',
    keywords: ['refresh rate test', 'hz test', 'fps test', 'display refresh checker'],
    iconType: 'gauge',
    requiredApis: ['requestAnimationFrame'],
    componentName: 'RefreshRateTester',
    relatedToolIds: ['screen-test', 'webcam-test', 'internet-speed-test'],
    instructions: [
      'Watch the live measurement stabilize over a few seconds.',
      'Compare the estimate against the HZ your monitor is configured for in OS settings.',
      'Close heavy background tabs; other work lowers the measured cadence.',
    ],
    limitations: [
      'This measures browser-rendering timing via requestAnimationFrame — it is not certification of the panel\u2019s specification or of gaming performance.',
      'A laptop on battery saver may be limited below its panel capability.',
    ],
    troubleshooting: [
      'Low reading? Check the OS display settings for the configured refresh rate.',
      'V-Sync or dynamic refresh features can make readings bounce between values.',
    ],
  },
  {
    id: 'internet-speed-test',
    slug: 'internet-speed-test',
    category: 'network' as ToolCategory,
    categoryLabel: 'Network',
    title: 'Internet Speed Test',
    shortDesc: 'Real download, upload, and latency measurements via the Cloudflare measurement network.',
    supportHint: 'Transfers real data on start',
    keywords: ['internet speed test', 'speed test', 'bandwidth test', 'wifi speed test', 'download speed'],
    iconType: 'gauge',
    requiredApis: ['Fetch API', 'PerformanceResourceTiming'],
    componentName: 'InternetSpeedTester',
    relatedToolIds: ['what-is-my-ip', 'refresh-rate-test', 'webcam-test'],
    supportLinks: [
      { label: 'Low result? What it means', href: '/guides/low-internet-speed-result' },
    ],
    instructions: [
      'Press Start — the test immediately transfers real data, which can consume significant mobile data.',
      'Watch download, upload, and latency stream in as each phase completes.',
      'Stay on this tab during the run; background throttling distorts measurements.',
    ],
    limitations: [
      'Results reflect the connection to the selected measurement network at that moment — other networks may differ.',
      'Latency here is HTTP round-trip timing to the measurement endpoint, not ICMP ping.',
      'Measurements are collected by the provider on completion for aggregated internet-quality insights.',
    ],
    troubleshooting: [
      'A surprisingly low result often means Wi-Fi interference — test near the router or on cable.',
      'Stop downloads, streaming, and cloud backups before running the test.',
    ],
  },
  {
    id: 'what-is-my-ip',
    slug: 'what-is-my-ip',
    category: 'network' as ToolCategory,
    categoryLabel: 'Network',
    title: "What's My IP",
    shortDesc: 'Show the public IP address your connection presents, with one-click copy.',
    supportHint: 'Tiny lookup request',
    keywords: ['what is my ip', 'my ip address', 'ip lookup', 'public ip', 'ipv4 ipv6'],
    iconType: 'gauge',
    requiredApis: ['Fetch API'],
    componentName: 'WhatsMyIpTester',
    relatedToolIds: ['internet-speed-test', 'refresh-rate-test', 'screen-test'],
    instructions: [
      'Press Show My IP to send one small request to the lookup endpoint.',
      'Copy the result with the copy button if you need it elsewhere.',
      'IPv4 and IPv6 are identified where the connection makes that reliable.',
    ],
    limitations: [
      'The result may be a VPN or proxy address rather than your home connection.',
      'No location, ISP, or identity information is looked up or shown.',
    ],
    troubleshooting: [
      'A request that never completes may be blocked by an extension or corporate proxy.',
      'VPN users: this shows the VPN exit address by design.',
    ],
  },
];

/**
 * Supporting diagnostics: real pages, kept out of the primary catalog.
 * They are linked contextually from tool pages and help content.
 */
export const SUPPORTING_REGISTRY: ToolDefinition[] = [
  {
    id: 'permission-diagnostics',
    slug: 'permission-diagnostics',
    category: 'supporting' as ToolCategory,
    categoryLabel: 'Supporting',
    title: 'Permission Diagnostics',
    shortDesc: 'Check and troubleshoot microphone and camera permission states in your browser.',
    supportHint: 'Permissions API',
    keywords: ['microphone permission', 'camera permission', 'camera blocked', 'mic blocked'],
    iconType: 'shield',
    requiredApis: ['Permissions API'],
    componentName: 'PermissionDiagnosticsTester',
    relatedToolIds: [],
    instructions: [
      'Open the page and read the current microphone and camera permission states.',
      'Follow the per-browser steps to allow access when a permission is denied.',
    ],
    limitations: ['Firefox may not report exact permission states for these devices.'],
    troubleshooting: [
      'Click the padlock in the address bar to reset a denied permission, then reload.',
    ],
  },
  {
    id: 'browser-compatibility',
    slug: 'browser-compatibility',
    category: 'supporting' as ToolCategory,
    categoryLabel: 'Supporting',
    title: 'Browser Compatibility',
    shortDesc: 'See which web APIs your browser supports before running hardware tests.',
    supportHint: 'Passive read-only checks',
    keywords: ['browser compatibility', 'api support', 'browser capabilities'],
    iconType: 'shield',
    requiredApis: [],
    componentName: 'BrowserCompatibilityTester',
    relatedToolIds: [],
    instructions: ['Scan the matrix, or search for a specific API by name.'],
    limitations: ['Feature presence does not guarantee a working implementation.'],
    troubleshooting: ['Update your browser if a required API is missing.'],
  },
  {
    id: 'codec-support',
    slug: 'codec-support',
    category: 'supporting' as ToolCategory,
    categoryLabel: 'Supporting',
    title: 'Codec Support',
    shortDesc: 'Check which audio and video codecs your browser can encode and decode.',
    supportHint: 'MediaCapabilities API',
    keywords: ['codec support', 'h264', 'video codec', 'call quality'],
    iconType: 'shield',
    requiredApis: ['MediaCapabilities'],
    componentName: 'CodecSupportTester',
    relatedToolIds: [],
    instructions: ['Review the decode/encode support table for common call codecs.'],
    limitations: ['Reported support does not guarantee hardware acceleration.'],
    troubleshooting: ['Missing H.264/VP8 support can degrade call quality; update the browser.'],
  },
  {
    id: 'webrtc-test',
    slug: 'webrtc-test',
    category: 'supporting' as ToolCategory,
    categoryLabel: 'Supporting',
    title: 'WebRTC Capability Test',
    shortDesc: 'Verify local WebRTC peer-connection capability for call apps — no leak testing.',
    supportHint: 'Local capability check only',
    keywords: ['webrtc test', 'webrtc support', 'video call diagnostic'],
    iconType: 'shield',
    requiredApis: ['RTCPeerConnection'],
    componentName: 'WebRTCTester',
    relatedToolIds: [],
    instructions: [
      'Run the check to confirm your browser can create peer connections and gather ICE candidates.',
    ],
    limitations: [
      'This is a local capability test. It is not a leak test and does not evaluate VPN or DNS behavior.',
    ],
    troubleshooting: ['Strict privacy extensions may block peer connections; disable them to retest.'],
  },
  {
    id: 'browser-system-info',
    slug: 'browser-system-info',
    category: 'supporting' as ToolCategory,
    categoryLabel: 'Supporting',
    title: 'Browser & System Info',
    shortDesc: 'User-agent, screen, and capability facts your browser chooses to expose.',
    supportHint: 'Read-only',
    keywords: ['browser info', 'system info', 'user agent', 'screen resolution'],
    iconType: 'shield',
    requiredApis: [],
    componentName: 'BrowserSystemInfoTester',
    relatedToolIds: [],
    instructions: ['Review the reported values; browsers increasingly reduce fingerprinting detail.'],
    limitations: [
      'Browsers expose only partial device information; this is not a complete device specification.',
    ],
    troubleshooting: ['Values vary by browser privacy settings — that is expected.'],
  },
  {
    id: 'devicetry-storage-inspector',
    slug: 'devicetry-storage-inspector',
    category: 'supporting' as ToolCategory,
    categoryLabel: 'Supporting',
    title: 'DeviceTry Storage Inspector',
    shortDesc: "Inspect and clear DeviceTry's local history and settings stored in your browser.",
    supportHint: 'Local storage only',
    keywords: ['clear data', 'local storage', 'privacy controls', 'delete history'],
    iconType: 'shield',
    requiredApis: ['localStorage'],
    componentName: 'PrivacyStorageInspectorTester',
    relatedToolIds: [],
    instructions: [
      'Review what DeviceTry has stored locally and clear it whenever you want.',
    ],
    limitations: ['Clearing local history cannot be undone.'],
    troubleshooting: ['If history will not save, your browser may be blocking site data.'],
  },
];

/** Every renderable tool page (primary + supporting). */
export const ALL_TOOL_PAGES: ToolDefinition[] = [...TOOLS_REGISTRY, ...SUPPORTING_REGISTRY];

export function findToolBySlug(slug: string): ToolDefinition | undefined {
  return ALL_TOOL_PAGES.find((tool) => tool.slug === slug);
}
